config/routes.rb
Rl::Application.routes.draw do
  resources :receivers

  resources :messages

  devise_for :admins

  resources :sponsors

  resources :orders

  devise_for :users
  
  devise_scope :user do
  get "logout" => "devise/sessions#destroy"
end 
  resources :menus

  root :to => "receivers#new"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/message.rb
class Message < ActiveRecord::Base
    has_and_belongs_to_many :receivers
end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
    has_and_belongs_to_many :messages
    validates_presence_of :name
    validates_presence_of :phone
    validates_presence_of :timezone
    #validates_presence_of :accepted_tos
    
    validates_uniqueness_of :phone

    attr_accessible :name, :phone, :timezone
    
    TIMES1 = ["6:00 AM", "6:30 AM", "7:00 AM", "7:30 AM", "8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM",
      "10:30 AM", "11:00 AM", "11:30 AM", "12:00 Noon", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM",
      "5:30 PM"]
    
    def rec_times
      return Receiver::TIMES1
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        
        has_many :orders
        belongs_to :sponsor
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, 
                  :delivery_location, :delivery_sub_location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :ok }
    end
  end
end

app/controllers/receivers_controller.rb
class ReceiversController < ApplicationController
  # GET /receivers
  # GET /receivers.json
  def index
    @receivers = Receiver.all
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receivers }
    end
    
  end

  # GET /receivers/1
  # GET /receivers/1.json
  def show
    @receiver = Receiver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receiver }
    end
  end

  # GET /receivers/new
  # GET /receivers/new.json
  def new
    @receiver = Receiver.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receiver }
    end
  end

  # GET /receivers/1/edit
  def edit
    @receiver = Receiver.find(params[:id])
  end

  # POST /receivers
  # POST /receivers.json
  def create
      
    @receiver = Receiver.new(params[:receiver])
   
    respond_to do |format|
      if @receiver.save
     #   format.html { redirect_to @receiver, notice: 'Receiver was successfully created.' }
        format.html { redirect_to root_path, notice: 'Receiver created. Please check your email to complete registration. Text messages will start soon. thanks' }
        format.json { render json: @receiver, status: :created, location: @receiver }
        
    @receiver.reload
    @rid = Receiver.last.id
     # p "**********************************"
   # p params
   # p "receiver id: " + @rid.to_s
    # p "message id: " + params[:message1][:id].to_s
    # p "message id: " + params[:message2][:id].to_s
    # p "**********************************"
    @sql1 = "insert into messages_receivers values ( #{@rid.to_s} , #{params[:message1][:id].to_s} )"  
    @sql2 = "insert into messages_receivers values ( #{@rid.to_s} , #{params[:message2][:id].to_s} )"  
    @sql3 = "insert into messages_receivers values ( #{@rid.to_s} , #{params[:message3][:id].to_s} )"  
    @sql4 = "insert into messages_receivers values ( #{@rid.to_s} , #{params[:message4][:id].to_s} )"  
    @sql5 = "insert into messages_receivers values ( #{@rid.to_s} , #{params[:message5][:id].to_s} )"  
    @sql6 = "insert into messages_receivers values ( #{@rid.to_s} , #{params[:message6][:id].to_s} )"  

    ActiveRecord::Base.connection.execute(@sql1)
    ActiveRecord::Base.connection.execute(@sql2)
    ActiveRecord::Base.connection.execute(@sql3)
    ActiveRecord::Base.connection.execute(@sql4)
    ActiveRecord::Base.connection.execute(@sql5)
    ActiveRecord::Base.connection.execute(@sql6)
    
    else
        format.html { render action: "new" }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PUT /receivers/1
  # PUT /receivers/1.json
  def update
    @receiver = Receiver.find(params[:id])

    respond_to do |format|
      if @receiver.update_attributes(params[:receiver])
        format.html { redirect_to @receiver, notice: 'Receiver was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @receiver.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  # DELETE /receivers/1
  # DELETE /receivers/1.json
  def destroy
    @receiver = Receiver.find(params[:id])
    @receiver.destroy

    respond_to do |format|
      format.html { redirect_to receivers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>sst</title>
  <%= stylesheet_link_tag 'application.css' %>
  <%= stylesheet_link_tag 'bootstrap.css' %>
  <%= javascript_include_tag 'application.js' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="<%=root_path %>">S T O P   S M O K I N G   T E X T</a>
            <ul class="nav">
                <li class="active"><a href="#"></a></li>
                <% if current_user.try(:admin?) %>
                <li><a href="<%= orders_path %>">Orders</a></li>
                <% end %>
                <li><a href="#"></a></li>
                <li><a href="#"></a></li>
          </ul>
          <ul class="class=navbar nav navbar-text pull-right">
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul> </div>
    </div>
     <%= link_to image_tag("sst_logo.gif",:style =>"height:90px;width:100%;", :alt =>"stop smoking text"), root_path %>
</div>
<div class="container">
<%= yield %>
</div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message_text %><br />
    <%= f.text_field :message_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="container">
  <h2>Setup Once & Send daily <strong>automatic</strong> texts to help stop smoking</h2>
  <h2 style="color: #ff0000"><%= params['msg'] %></h2>
  <h4><strong>One Time</strong> Setup is as easy as 1 - 2 - 3</h4>
  <%#= form_for :receiver, :url => save_receiver_data_url do |f| %>
  <%= form_for :receiver,  do |f| %>
  <%#= f.error_messages %>
  <p>
<table class="zebra-striped">
    <tr> <td> 1.  Text Recepient Phone Number <%=f.text_field :phone %>
      and Name: <%=f.text_field :name %> </td></tr>
      <tr> <td> 2. Where is the recipient: <%#=time_zone_select( "receiver", "timezone", ActiveSupport::TimeZone.us_zones, :default => "Pacific Time (US & Canada)") %> <br/>
      Pacific Time (CA) <%= check_box_tag 'timezone', 'Pacific' %>
      Arizona Time <%= check_box_tag 'Arizona', :timezone %>
      Mountain Time (CO) <%= check_box_tag 'Mountain', :timezone %>
      Central Time (IL)<%= check_box_tag 'Central', :timezone %>
      Eastern Time (NY)<%= check_box_tag 'Eastern', :timezone %> </td></tr>
       <tr> <td>3. When do you want the person to receive the text messages </br>
       Morning (AM): 6:00 <%= check_box_tag 'texttime'%> 6:30 <%= check_box_tag 'texttime'%> 7:00 <%= check_box_tag 'texttime'%>
    7:30 <%= check_box_tag 'texttime'%> 8:00 <%= check_box_tag 'texttime'%> 8:30 <%= check_box_tag 'texttime'%>
     9:00 <%= check_box_tag 'texttime'%> 9:30 <%= check_box_tag 'texttime'%> 10:00 <%= check_box_tag 'texttime'%>
    10:30 <%= check_box_tag 'texttime'%> 11:00 <%= check_box_tag 'texttime'%> 11:30 <%= check_box_tag 'texttime'%>
    12:00 <%= check_box_tag 'texttime'%> </td></tr>
    <tr> <td>  Afternoon (PM): 12:30 <%= check_box_tag 'texttime'%> 1:00 <%= check_box_tag 'texttime'%> 1:30 <%= check_box_tag 'texttime'%>
    2:00 <%= check_box_tag 'texttime'%> 2:30 <%= check_box_tag 'texttime'%> 3:00 <%= check_box_tag 'texttime'%>
     3:30 <%= check_box_tag 'texttime'%> 4:00 <%= check_box_tag 'texttime'%> 4:30 <%= check_box_tag 'texttime'%>
    5:00 <%= check_box_tag 'texttime'%> 5:30 <%= check_box_tag 'texttime'%> 6:00 <%= check_box_tag 'texttime'%>
    6:30 <%= check_box_tag 'texttime'%> </br> 7:00 <%= check_box_tag 'texttime'%>  7:30 <%= check_box_tag 'texttime'%>
  8:00 <%= check_box_tag 'texttime'%>  8:30 <%= check_box_tag 'texttime'%>  9:00 <%= check_box_tag 'texttime'%>
9:30 <%= check_box_tag 'texttime'%>  10:00 <%= check_box_tag 'texttime'%>  10:30 <%= check_box_tag 'texttime'%>
11:00 <%= check_box_tag 'texttime'%>  11:30 <%= check_box_tag 'texttime'%>  12:00 <%= check_box_tag 'texttime'%></br>
</td></tr>
</table>  
  </p>
    <% end %>
  </div>

<table class="zebra-striped">
  <tr>
    <th>Message text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= check_box_tag 'messages[]', message.id %>
    <%= message.message_text %></td>
    <td><%#= link_to 'Show', message %></td>
    <td><%#= link_to 'Edit', edit_message_path(message) %></td>
    <td><%#= link_to 'Destroy', message, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<% if user_signed_in? %>
    <td> <%= button_to ' Order ', orders_path(user_id: current_user), :class=>"btn primary large" %> </td>
    <% else %>
         <td> <%= button_to ' Login to Try - 10 days free then 25 cents per day ', root_path, :class=>"btn primary large" %> </td>
    <% end %>
<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message text:</b>
  <%= @message.message_text %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/receivers/_form.html.erb
<%= form_for(@receiver) do |f| %>
  <% if @receiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receiver.errors.count, "error") %> prohibited this receiver from being saved:</h2>

      <ul>
      <% @receiver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :timezone %><br />
    <%= f.text_field :timezone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receivers/edit.html.erb
<h1>Editing receiver</h1>

<%= render 'form' %>

<%= link_to 'Show', @receiver %> |
<%= link_to 'Back', receivers_path %>

app/views/receivers/index.html.erb
<h1>Listing receivers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Timezone</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receivers.each do |receiver| %>
  <tr>
    <td><%= receiver.name %></td>
    <td><%= receiver.phone %></td>
    <td><%= receiver.timezone %></td>
    <td><%= receiver.user_id %></td>
    <td><%= link_to 'Show', receiver %></td>
    <td><%= link_to 'Edit', edit_receiver_path(receiver) %></td>
    <td><%= link_to 'Destroy', receiver, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Receiver', new_receiver_path %>

app/views/receivers/new.html.erb
<div class="content">
  <br/><br/><br/><br/><br/><br/><br/>
  <h3>Setup it up Once & Send daily <strong>automatic</strong> texts to </br>help your loved one stop smoking</h3>
  <h4><strong>One Time</strong> Setup is as easy as 1 - 2 - 3</h4></br>
  <div class="row">
<div class="span12"> 
<%= form_for(@receiver) do |f|  %>
  <% if @receiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receiver.errors.count, "error") %> prohibited this receiver from being saved:</h2>

      <ul>
      <% @receiver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   
  <table class="table-striped table-condensed">
  <tr><td><%= f.label :name, 'Enter Recipient Name:', :class => "label info" %> 
    <%= f.text_field :name, :placeholder => 'Mom or Dad or Debbie or Dave' %></td> 
  <td>
    <%= f.label :phone, 'and Phone Number:' , :class => "label info" %> 
    <%= f.text_field :phone, :placeholder => '123-456-7890' %>
</td>
<td>&nbsp</td>
<td>&nbsp</td>
</tr>
   <tr><td>
    <%= f.label :timezone, 'Select Timezone', :class => "label info" %>  </td></tr>
   <tr ><td class="span2">  <%= f.radio_button :timezone, 'pacific', :class=>'radio inline' %>
  <%= f.label :Pacific %>  </td>
 <td class="span2"><%= f.radio_button :timezone, 'mountain' %>
  <%= f.label :Mountain %></td>
<td class="span2"><%= f.radio_button :timezone, 'central' %> <%= f.label :Central %>
  </td>
  <td class="span2"><%= f.radio_button :timezone, 'eastern' %><%= f.label :Eastern %>
  </td>
</tr>
</table>   
</div>
    
    <%#= f.label :user_id %> 
    <%#= f.number_field :user_id %>
<div class="row">
  <div class="span12">
  <h2 class="label info span10"> Text Messages - When to send and what to say </h2>
    <div class="span3">
        <table class="table-striped table-condensed">
        <tr><td> <%= f.select(:t1, Receiver::TIMES1, {:include_blank => false, :selected => "7:00 AM"}) %></td></tr>
        <tr><td> <%= f.select(:t2, Receiver::TIMES1, {:include_blank => false, :selected => "9:00 AM"}) %></td></tr>
        <tr><td> <%= f.select(:t3, Receiver::TIMES1, {:include_blank => false, :selected => "11:30 AM"}) %></td></tr>
        <tr><td> <%= f.select(:t4, Receiver::TIMES1, {:include_blank => false, :selected => "1:00 PM"}) %></td></tr>
        <tr><td> <%= f.select(:t5, Receiver::TIMES1, {:include_blank => false, :selected => "3:00 PM"}) %></td></tr>
        <tr><td> <%= f.select(:t6, Receiver::TIMES1, {:include_blank => false, :selected => "5:30 PM"}) %></td></tr>
        </table>  
    </div>   
    <div class="span4">
   <table class="table-striped table-condensed">
    <tr><td> <%=select('message1', "id", Message.all.collect {|m| [ m.message_text, m.id ] }, {:include_blank => false, :selected => "1"}, :class=>"span6") %></td></tr>
    <tr><td> <%=select("message2", "id", Message.all.collect {|m| [ m.message_text, m.id ] }, {:include_blank => false , :selected => "2"}, :class=>"span6") %></td></tr>
<tr><td> <%=select("message3", "id", Message.all.collect {|m| [ m.message_text, m.id ] }, {:include_blank => false, :selected => "3"}, :class=>"span6")%></td></tr>  
<tr><td> <%=select("message4", "id", Message.all.collect {|m| [ m.message_text, m.id ] }, {:include_blank => false, :selected => "4"}, :default =>"3" , :class=>"span6")%></td></tr>  
<tr><td> <%=select("message5", "id", Message.all.collect {|m| [ m.message_text, m.id ] }, {:include_blank => false, :selected => "5"}, :class=>"span6") %></td></tr>
<tr><td> <%=select("message6", "id", Message.all.collect {|m| [ m.message_text, m.id ] }, {:include_blank => false, :selected => "6"}, :class=>"span6") %></td></tr>
     </table>  
    </div>  
</div> 
</div>
  

<% if signed_in? %> </br>
    <div class="span12">
<%= f.check_box :accepted_tos %> I agree to the terms and conditions </br>
<%= f.submit 'Create Recipient', :class=>'btn primary large'%>
<% else %>
<%= link_to  "sign up to get started. first 10 days free - no credit card. 25 cents per day afterwards.", :new_user_registration, :class=>'btn primary large span10'%>
<% end %>
</div>

<% end %>
</div>

app/views/receivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @receiver.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @receiver.phone %>
</p>

<p>
  <b>Timezone:</b>
  <%= @receiver.timezone %>
</p>

<p>
  <b>User:</b>
  <%= @receiver.user_id %>
</p>


<%= link_to 'Edit', edit_receiver_path(@receiver) %> |
<%= link_to 'Back', receivers_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>